name: Mi Primer Inspector Automático

# ¿Cuándo se activa? (El disparador)
on:
  push:
    branches: ["main"] # Nota: si tu rama principal se llama master, cambia main por master

# ¿Qué tareas va a hacer?
jobs:
  inspeccion-inicial:
    # Le damos una computadora virtual en la nube para que trabaje (una cocina limpia)
    runs-on: ubuntu-latest

    # Pasos que va a seguir el inspector uno por uno
    steps:
      # Paso 1: Traer nuestro código de GitHub a esta computadora virtual
      - name: Obtener el codigo
        uses: actions/checkout@v4

      # Paso 2: Una simulación de prueba de calidad
      - name: Checkear la calidad del codigo
        run: echo "¡El inspector automático dice que el código está perfecto!"
